{% set name = "apache-airflow-providers-grpc" %}
{% set version = "3.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_grpc-{{ version }}.tar.gz
  sha256: 2bbc2d08212bd2a6099b7f0348bfc57cf73a850dadb6c5313c225af44f45b7a6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core ==3.10.0
    - pip
  run:
    - python >={{ python_min }},<4.dev0
    - apache-airflow >=2.9.0
    - google-auth-httplib2 >=0.0.1
    - google-auth >=1.0.0,<3.0.0
    - grpcio >=1.59.0

test:
  imports:
    - airflow.providers.grpc
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-grpc for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/grpc/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-grpc/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
