{% set name = "apache-airflow-providers-grpc" %}
{% set version = "1.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://archive.apache.org/dist/airflow/providers/{{ name }}-{{ version }}.tar.gz
  sha256: 47c3206461aaaef0e414cdc89173fa93ef89d7d30162d481b7fbfb326922da29

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
    - wheel
  run:
    - apache-airflow >=2.0.0
    - google-auth >=1.0.0,<2.0.0dev
    - google-auth-httplib2 >=0.0.1
    - grpcio >=1.15.0
    - python >=3.6

test:
  imports:
    - airflow.providers.grpc
    - airflow.providers.grpc.hooks
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for gRPC for Apache Airflow
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-grpc/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
