{% set name = "apache-airflow-providers-grpc" %}
{% set version = "2.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://archive.apache.org/dist/airflow/providers/{{ name }}-{{ version }}.tar.gz
  sha256: 319c7e74b15376d8d90eb3edfd0f9ee134274ffdcc8e23806f7431d67ac38808

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.6
    - apache-airflow >=2.1.0
    - google-auth >=1.0.0,<2.0.0dev
    - google-auth-httplib2 >=0.0.1
    - grpcio >=1.15.0

test:
  imports:
    - airflow.providers.grpc
    - airflow.providers.grpc.hooks
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for gRPC for Apache Airflow
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-grpc/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
