{% set name = "apache-airflow-providers-grpc" %}
{% set version = "3.8.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_grpc-{{ version }}.tar.gz
  sha256: 56298613df224152689893966a8cc3d2c9887bf4b0afbd295f989b44b309009e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core ==3.12.0
    - pip
  run:
    - python >={{ python_min }},<4.dev0
    - apache-airflow >=2.10.0
    - google-auth >=1.0.0,<3.0.0
    - google-auth-httplib2 >=0.0.1
    - grpcio >=1.59.0

test:
  imports:
    - airflow.providers.grpc
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-grpc for Apache Airflow
  license: Apache-2.0
  license_file: src/airflow/providers/grpc/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-grpc/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
